[package]
name = "dnd-emu"
version = "0.1.0"
authors = ["kyler-nelson <relyk92@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4.3"
serde = { version = "1.0.104", features = ["derive"] }
